In [2]:
#数据排序 df.sort_values()  进行升序和降序排序
import pandas as pd
df = pd.read_csv(r'D:\github\python-noob\数据分析\data01.csv',encoding='utf-8')
pd.set_option('display.max_rows',20)
df.sort_values('年龄',ascending=True)  #升序,ascending=False降序
df.sort_values(['年龄','工资'],ascending=[True,True])

    ID             姓名   年龄     工资        参加时间
7    8   Frank Miller   10  70000  2021-12-05
34  34  Fiona Stewart   20  82000  2020-10-31
26  26      Xena Hill   24  44000  2022-09-18
0    1       John Doe   25  50000  2020-01-15
10   1       John Doe   25  50000  2020-01-15
..  ..            ...  ...    ...         ...
12  12  Jack Anderson   48  72000  2017-08-09
23  23   Ulysses King   50  85000  2017-03-15
4    1  Charlie Brown   52  50000  2018-07-22
25  25  William Lopez   55  92000  2016-06-07
14  14   Leo Martinez  150  83000  2021-02-28

[36 rows x 5 columns]

In [ ]:
#数据分组
import pandas as pd
df = pd.read_csv('data02.csv')
#根据产品类别进行分组并统计产品名称数量
df.groupby('产品类别')['产品名称'].count()
#根据产品类别进行分组并统计销售数量之和
df.groupby('产品类别')['销售数量'].sum()
#根据产品类别进行分组并统计销售金额之和
df['销售金额'] = df['销售数量']*df['单价']
df.groupby('产品类别')['销售金额'].sum()
#根据产品类别进行分组并统计销售商品平均值
df.groupby('产品类别')['单价'].mean()
#根据产品类别进行分组并统计销售商品最大值
df.groupby('产品类别')['单价'].max()
#根据产品类别进行分组并统计销售商品最小值
df.groupby('产品类别')['单价'].min()
#根据产品类别进行分组并统计销售商品最小值,最大值,平均值
df.groupby('产品类别')['单价'].agg(['min','max','mean']).round(2)
df.groupby('产品类别').agg({'单价':['min','max','mean']}).round(2)
#根据产品类别进行分组并统计销售数量之和,销售金额之和，平均单价
df.groupby('产品类别').agg({'销售数量':'sum', '销售金额':'sum', '单价':'mean'}).round(2)

      单价
     min   max    mean
产品类别
家居用品  35   358  132.43
服装    79   399  176.50
电子产品  89  2999  944.00
食品    29   128   73.29